### ISSUE TITLE
Integration of free reservation time (60 min)

### ISSUE THREAD

**Issue by Fabimeric** [bet-smart-parking/smart-parking-backend#20]
As designed in the [prototype](https://www.figma.com/proto/ugzf5ZRhOVqPVcDkL6MKMl/ProtoType-v2?node-id=1%3A7&scaling=contain), we need a free reservation time of max. 60 minutes. The timer runs from 60 to 0 minutes. As soon as the time is up, a respective (timeout) message will appear (check screenshot). From there, the user can jump back to the first screen and start a new reservation.

![image](https://user-images.githubusercontent.com/22399153/77763985-2fc4d980-703c-11ea-8443-0a00975c67f6.png)

**Comment by hirsch88** [comment]
736787
